Add Support for MacOS
deltacasttv/video-viewer pull request #23
Opened 2024-12-05 15:33 UTC by Isard7777

Close #9

2024-12-13 16:03 UTC, Isard7777 commented
Ideally, I'd still like to do the yuvk -> rgba conversion in a separate shader to avoid redundancy in the other shaders, but I think I've already used up the budget.

2024-12-16 08:04 UTC, julienalofs requested changes
Since you changed the shaders, did you validate all packing conversion in all supported video resolution?

2024-12-16 08:04 UTC, julienalofs commented on src/videoviewer_internal.cpp
> +    : m_compute_shader(std::make_unique<Shader>()),
Shouldn't this variable `m_compute_shader` be renamed?

2024-12-16 08:04 UTC, julienalofs commented on src/videoviewer_internal.cpp
> +    {{-1.0f, -1.0f},  {0.0f, 0.0f}}, // {triangle vertices x, y} , {texture x, y}
Can't we avoid vertices flip by changing those vertices coordinates?

2024-12-16 10:41 UTC, Isard7777 commented
> Since you changed the shaders, did you validate all packing conversions in all supported video resolutions?

I have validated my development (including all pixel formats, especially YUV 422 10-bit) on the following resolutions:

720x480
720x576
1280x720
1920x1080
2048x1536
3840x2160
4096x2160
All formats are working as expected, except for YUV 422 10-bit with MSB issues on 720p, 2048x1536, and 4096x2160. Upon investigation, I found that this issue was already present prior to my changes.

I will explore whether specific shaders can be introduced for these formats, as we have done previously in dScope.

2024-12-16 16:24 UTC, julienalofs commented on sample/colorbar.hpp
> +         bgr_444_8_le_msb, /*< BGR 4:4:4 8bit little endian with msb padding (30/32 bits) */
24/32

2024-12-16 16:25 UTC, julienalofs commented on src/videoviewer_internal.cpp
> +   m_conversion_shader->compile(std::string(vertex_shader_flip_vertices), std::string(compute_shader_name));
compute_shader_name aussi à renommer

2024-12-16 16:26 UTC, julienalofs commented on sample/main.cpp
> +   int texture_width = 720;
C'est volontaire d'avoir rentré ces modifications dans le sample ?

2024-12-17 09:30 UTC, Isard7777 commented
> > Since you changed the shaders, did you validate all packing conversions in all supported video resolutions?
> 
> I have validated my development (including all pixel formats, especially YUV 422 10-bit) on the following resolutions:
> 
> 720x480 720x576 1280x720 1920x1080 2048x1536 3840x2160 4096x2160 All formats are working as expected, except for YUV 422 10-bit with MSB issues on 720p, 2048x1536, and 4096x2160. Upon investigation, I found that this issue was already present prior to my changes.
> 
> I will explore whether specific shaders can be introduced for these formats, as we have done previously in dScope.

Since I wasn't able to implement this quickly enough, I created an issue to address the problem later, in accordance with our discussion.

2024-12-17 10:46 UTC, julienalofs approved these changes

2024-12-18 08:30 UTC, merged